from pathlib import Path


current_directory = Path(__file__).parent.resolve()
move_action = current_directory.joinpath("step.png")
pass_action = current_directory.joinpath("armor-0.png")
healing_hand = current_directory.joinpath("heal-jade-3.png")
light_shield = current_directory.joinpath("protect-sky-1.png")
medium_shield = current_directory.joinpath("protect-sky-2.png")
great_shield = current_directory.joinpath("protect-sky-3.png")
ds_sword = current_directory.joinpath("w_longsword_gold.png")
dagger = current_directory.joinpath("w_dagger_steel.png")
two_daggers = current_directory.joinpath("w_dagger_gold.png")
sword_oh = current_directory.joinpath("w_shortsword_steel.png")
sword_bastard = current_directory.joinpath("w_longsword_steel.png")
sword_th = current_directory.joinpath("w_broadsword_steel.png")
axe = current_directory.joinpath("w_axe_war_steel.png")
bow = current_directory.joinpath("archer.png")
fists = current_directory.joinpath("wind-grasp-air-1.png")
divine_smite_spell = current_directory.joinpath("slice-orange-3.png")
fire_ball_spell = current_directory.joinpath("fireball-red-2.png")
faery_tale_spell = current_directory.joinpath("horror-eerie-3.png")
ice_storm_spell = current_directory.joinpath("ice-blue-3.png")
shadow_blade_spell = current_directory.joinpath("enchant-magenta-3.png")
magic_missile_spell = current_directory.joinpath("fire-arrows-magenta-3.png")
sacrifice = current_directory.joinpath("runes-orange-3.png")
bear_paws_spell = current_directory.joinpath("wild-acid-3.png")
fire_storm_spell = current_directory.joinpath("wind-red-3.png")
