from src.utils.tools import Characteristic, Character, Textures
from src.utils.descriptions import (
    BARBARIAN_DESC,
    BARD_DESC,
    CLERIC_DESC,
    DRUID_DESC,
    FIGHTER_DESC,
    MONK_DESC,
    PALADIN_DESC,
    RANGER_DESC,
    ROGUE_DESC,
    SORCERER_DESC,
    WARLOCK_DESC,
    WIZARD_DESC,
)
from src.utils.textures import (
    UNIT_SPRITE_SHEET,
    BARBARIAN_MALE_RECT,
    BARBARIAN_FEMALE_RECT,
    BARD_MALE_RECT,
    BARD_FEMALE_RECT,
    CLERIC_MALE_RECT,
    CLERIC_FEMALE_RECT,
    DRUID_MALE_RECT,
    DRUID_FEMALE_RECT,
    FIGHTER_MALE_RECT,
    FIGHTER_FEMALE_RECT,
    MONK_MALE_RECT,
    MONK_FEMALE_RECT,
    PALADIN_MALE_RECT,
    PALADIN_FEMALE_RECT,
    RANGER_MALE_RECT,
    RANGER_FEMALE_RECT,
    ROGUE_MALE_RECT,
    ROGUE_FEMALE_RECT,
    SORCERER_MALE_RECT,
    SORCERER_FEMALE_RECT,
    WARLOCK_MALE_RECT,
    WARLOCK_FEMALE_RECT,
    WIZARD_MALE_RECT,
    WIZARD_FEMALE_RECT,
)

barbarian = Character(
    name="Barbarian",
    title="Варвар",
    description=BARBARIAN_DESC,
    characteristic=Characteristic(
        strength=16,
        constitution=16,
        dexterity=10,
        intelligence=8,
        wisdom=8,
        charisma=8,
        base_hit_points=10,
        base_hp_coefficient=5,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=BARBARIAN_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=BARBARIAN_FEMALE_RECT),
    ),
)

bard = Character(
    name="Bard",
    title="Бард",
    description=BARD_DESC,
    characteristic=Characteristic(
        strength=8,
        constitution=8,
        dexterity=16,
        intelligence=10,
        wisdom=8,
        charisma=16,
        base_hit_points=8,
        base_hp_coefficient=4,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=BARD_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=BARD_FEMALE_RECT),
    ),
)
cleric = Character(
    name="Cleric",
    title="Жрец",
    description=CLERIC_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=16,
        dexterity=8,
        intelligence=8,
        wisdom=16,
        charisma=8,
        base_hit_points=12,
        base_hp_coefficient=6,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=CLERIC_FEMALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=CLERIC_MALE_RECT),
    ),
)
druid = Character(
    name="Druid",
    title="Друид",
    description=DRUID_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=12,
        dexterity=12,
        intelligence=8,
        wisdom=8,
        charisma=16,
        base_hit_points=10,
        base_hp_coefficient=5,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=DRUID_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=DRUID_FEMALE_RECT),
    ),
)
fighter = Character(
    name="Fighter",
    title="Воин",
    description=FIGHTER_DESC,
    characteristic=Characteristic(
        strength=16,
        constitution=14,
        dexterity=12,
        intelligence=8,
        wisdom=8,
        charisma=8,
        base_hit_points=10,
        base_hp_coefficient=5,
        base_crit_chance=2,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=FIGHTER_FEMALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=FIGHTER_MALE_RECT),
    ),
)
monk = Character(
    name="Monk",
    title="Монах",
    description=MONK_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=14,
        dexterity=16,
        intelligence=8,
        wisdom=10,
        charisma=8,
        base_hit_points=10,
        base_hp_coefficient=5,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=MONK_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=MONK_FEMALE_RECT),
    ),
)
paladin = Character(
    name="Paladin",
    title="Паладин",
    description=PALADIN_DESC,
    characteristic=Characteristic(
        strength=16,
        constitution=10,
        dexterity=10,
        intelligence=8,
        wisdom=8,
        charisma=14,
        base_hit_points=10,
        base_hp_coefficient=4,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=PALADIN_FEMALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=PALADIN_MALE_RECT),
    ),
)
ranger = Character(
    name="Ranger",
    title="Лучник",
    description=RANGER_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=12,
        dexterity=16,
        intelligence=10,
        wisdom=10,
        charisma=8,
        base_hit_points=8,
        base_hp_coefficient=4,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=RANGER_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=RANGER_FEMALE_RECT),
    ),
)
rogue = Character(
    name="Rogue",
    title="Убийца",
    description=ROGUE_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=10,
        dexterity=16,
        intelligence=10,
        wisdom=10,
        charisma=10,
        base_hit_points=8,
        base_hp_coefficient=3,
        base_crit_chance=3,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=ROGUE_FEMALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=ROGUE_MALE_RECT),
    ),
)
sorcerer = Character(
    name="Sorcerer",
    title="Чародей",
    description=SORCERER_DESC,
    characteristic=Characteristic(
        strength=8,
        constitution=12,
        dexterity=12,
        intelligence=16,
        wisdom=8,
        charisma=10,
        base_hit_points=8,
        base_hp_coefficient=3,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=SORCERER_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=SORCERER_FEMALE_RECT),
    ),
)
warlock = Character(
    name="Warlock",
    title="Колдун",
    description=WARLOCK_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=12,
        dexterity=12,
        intelligence=8,
        wisdom=16,
        charisma=8,
        base_hit_points=6,
        base_hp_coefficient=3,
        base_crit_chance=2,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=WARLOCK_FEMALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=WARLOCK_MALE_RECT),
    ),
)
wizard = Character(
    name="Wizard",
    title="Волшебник",
    description=WIZARD_DESC,
    characteristic=Characteristic(
        strength=10,
        constitution=10,
        dexterity=10,
        intelligence=16,
        wisdom=10,
        charisma=10,
        base_hit_points=8,
        base_hp_coefficient=3,
    ),
    textures=Textures(
        day=UNIT_SPRITE_SHEET.get_texture(rect=WIZARD_MALE_RECT),
        night=UNIT_SPRITE_SHEET.get_texture(rect=WIZARD_FEMALE_RECT),
    ),
)
