"""Базовая информация"""

# Ширина/высота клетки в пикселях
CELL_SIZE = 100
WINDOW_WIDTH = CELL_SIZE * 10
WINDOW_HEIGHT = CELL_SIZE * 8
WINDOW_TITLE = "DnD-Chess"
DEFAULT_FONT_SIZE = 12
DEFAULT_FONT_NAME = "Kenney Pixel Square"
DEFAULT_TEXT_WIDTH = CELL_SIZE * 3

# базовые значения костей
BASE_CRITICAL_ROLL = 99
CRITICAL_DICE_SIDE = 20
SAVE_THROW_DICE_SIDE = 20
SPELL_ROLL_DIFFICULTY = 10
WEAPON_ROLL_DIFFICULTY = 20
CRITICAL_ROLL_RESISTANCE = 20

# базовые значения бонусов
BASE_DOMAIN_POWER = 12

# базовые характеристики персонажей
BASE_CHARACTERISTIC = 10
BASE_HIT_POINTS = 10
BASE_HP_COEFFICIENT = 5
BASE_HIT_CHANCE = 0
BASE_DEFENCE = 10
BASE_CRIT_CHANCE = 0
BASE_CRIT_RESISTANCE = 0
BASE_MAGIC_RESISTANCE = 0
