from arcade import load_texture, load_spritesheet, LRBT

# текстуры кнопок
SWITCH_GREEN_TEXTURE = load_texture(file_path=":resources:gui_basic_assets/toggle/green.png")
SWITCH_RED_TEXTURE = load_texture(file_path=":resources:gui_basic_assets/toggle/red.png")
RED_BUTTON_NORMAL_TEXTURE = load_texture(file_path=":resources:gui_basic_assets/button/red_normal.png")
RED_BUTTON_HOVER_TEXTURE = load_texture(file_path=":resources:gui_basic_assets/button/red_hover.png")
RED_BUTTON_PRESS_TEXTURE = load_texture(file_path=":resources:gui_basic_assets/button/red_press.png")

# текстуры зданий
ALTAR_TEXTURE = load_texture(file_path="src/sprites/buildings/Altar.png")
CASTLE_TEXTURE = load_texture(file_path="src/sprites/buildings/Castle.png")
CRYPT_TEXTURE = load_texture(file_path="src/sprites/buildings/Crypt.png")

# Текстуры доменов
RED_DOMAIN_TEXTURE = load_texture(file_path=":resources:images/tiles/lava.png")
BLUE_DOMAIN_TEXTURE = load_texture(file_path=":resources:images/tiles/water.png")
GRAY_DOMAIN_TEXTURE = load_texture(file_path=":resources:images/tiles/brickGrey.png")

# текстуры фигур
# BARBARIAN_TEXTURE = load_texture(file_path="src/sprites/units/Barbarian.png")
# BARD_TEXTURE = load_texture(file_path="src/sprites/units/Bard.png")
# CLERIC_TEXTURE = load_texture(file_path="src/sprites/units/Cleric.png")
# DRUID_TEXTURE = load_texture(file_path="src/sprites/units/Druid.png")
# FIGHTER_TEXTURE = load_texture(file_path="src/sprites/units/Fighter.png")
# MONK_TEXTURE = load_texture(file_path="src/sprites/units/Monk.png")
# PALADIN_TEXTURE = load_texture(file_path="src/sprites/units/Paladin.png")
# RANGER_TEXTURE = load_texture(file_path="src/sprites/units/Ranger.png")
# ROGUE_TEXTURE = load_texture(file_path="src/sprites/units/Rogue.png")
# SORCERER_TEXTURE = load_texture(file_path="src/sprites/units/Sorcerer.png")
# WARLOCK_TEXTURE = load_texture(file_path="src/sprites/units/Warlock.png")
# WIZARD_TEXTURE = load_texture(file_path="src/sprites/units/Wizard.png")
# через один рисунок
UNIT_SPRITE_SHEET = load_spritesheet("src/sprites/units/dnd_units.png")
# и позиции текстур на этом рисунке (в пикселях)
BARBARIAN_MALE_RECT = LRBT(left=10, right=175, bottom=730, top=900)
BARBARIAN_FEMALE_RECT = LRBT(left=175, right=340, bottom=720, top=900)
BARD_MALE_RECT = LRBT(left=380, right=530, bottom=580, top=725)
BARD_FEMALE_RECT = LRBT(left=530, right=705, bottom=570, top=725)
CLERIC_MALE_RECT = LRBT(left=345, right=520, bottom=930, top=1065)
CLERIC_FEMALE_RECT = LRBT(left=540, right=680, bottom=930, top=1065)
DRUID_MALE_RECT = LRBT(left=335, right=490, bottom=10, top=175)
DRUID_FEMALE_RECT = LRBT(left=505, right=685, bottom=15, top=180)
FIGHTER_MALE_RECT = LRBT(left=180, right=345, bottom=920, top=1065)
FIGHTER_FEMALE_RECT = LRBT(left=15, right=180, bottom=920, top=1065)
MONK_MALE_RECT = LRBT(left=20, right=160, bottom=570, top=725)
MONK_FEMALE_RECT = LRBT(left=175, right=330, bottom=590, top=720)
PALADIN_MALE_RECT = LRBT(left=340, right=520, bottom=720, top=900)
PALADIN_FEMALE_RECT = LRBT(left=515, right=690, bottom=730, top=900)
RANGER_MALE_RECT = LRBT(left=35, right=185, bottom=405, top=570)
RANGER_FEMALE_RECT = LRBT(left=185, right=365, bottom=420, top=570)
ROGUE_MALE_RECT = LRBT(left=380, right=530, bottom=430, top=565)
ROGUE_FEMALE_RECT = LRBT(left=555, right=680, bottom=415, top=565)
SORCERER_MALE_RECT = LRBT(left=45, right=165, bottom=220, top=390)
SORCERER_FEMALE_RECT = LRBT(left=195, right=310, bottom=225, top=390)
WARLOCK_MALE_RECT = LRBT(left=360, right=500, bottom=220, top=390)
WARLOCK_FEMALE_RECT = LRBT(left=500, right=635, bottom=220, top=390)
WIZARD_MALE_RECT = LRBT(left=50, right=165, bottom=50, top=170)
WIZARD_FEMALE_RECT = LRBT(left=185, right=310, bottom=50, top=170)

# иконки действий
MOVE_ACTION_TEXTURE = load_texture(file_path="src/sprites/perks/blazing-feet.png")
PASS_ACTION_TEXTURE = load_texture(file_path="src/sprites/perks/armor-0.png")

# иконки способностей
HEALING_HAND_TEXTURE = load_texture(file_path="src/sprites/perks/heal-jade-3.png")
LIGHT_SHIELD_TEXTURE = load_texture(file_path="src/sprites/perks/protect-sky-1.png")
MEDIUM_SHIELD_TEXTURE = load_texture(file_path="src/sprites/perks/protect-sky-2.png")
GREAT_SHIELD_TEXTURE = load_texture(file_path="src/sprites/perks/protect-sky-3.png")
DS_SWORD_TEXTURE = load_texture(file_path="src/sprites/perks/w_longsword_gold.png")
DAGGER_TEXTURE = load_texture(file_path="src/sprites/perks/w_dagger_steel.png")
TWO_DAGGERS_TEXTURE = load_texture(file_path="src/sprites/perks/w_dagger_gold.png")
SWORD_OH_TEXTURE = load_texture(file_path="src/sprites/perks/w_shortsword_steel.png")
SWORD_BASTARD_TEXTURE = load_texture(file_path="src/sprites/perks/w_longsword_steel.png")
SWORD_TH_TEXTURE = load_texture(file_path="src/sprites/perks/w_broadsword_steel.png")
AXE_TEXTURE = load_texture(file_path="src/sprites/perks/w_axe_war_steel.png")
BOW_TEXTURE = load_texture(file_path="src/sprites/perks/archer.png")
FISTS_TEXTURE = load_texture(file_path="src/sprites/perks/wind-grasp-air-1.png")
D_S_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/slice-orange-3.png")
F_B_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/fireball-red-2.png")
F_T_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/horror-eerie-3.png")
I_S_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/ice-blue-3.png")
S_B_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/enchant-magenta-3.png")
M_M_SPELL_TEXTURE = load_texture(file_path="src/sprites/perks/fire-arrows-magenta-3.png")
